### PR TITLE
Write Code Documentations

### LINKED ISSUE #69: Write Code Documentations for Public APIs available in the SDK

### PR DESCRIPTION
**Pull request by mayorjay**
Closes #69

### CODE REVIEW

**Comment by mayorJAY** [comment]
@unicodeveloper @Cliftonz Pls review this

**Comment by Cliftonz** [comment]
@SokratisVidros

**Review by SokratisVidros — APPROVED** [review]

**Comment by Cliftonz** [comment]
@SokratisVidros You still need to merge these, the contributor does not have access to merge

**Comment by SokratisVidros** [comment]
Thanks for the reminder @Cliftonz!

**Pull request merged**
